import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "..", "contracts", "out");
const DEST = join(here, "..", "lib", "abis.ts");
const CONTRACTS = ["CampaignEscrow", "AuctionHouse", "AttestcoinSettlement", "SourceEngagement", "MockUSDC"];
if (!existsSync(OUT)) { console.error("run `forge build` in contracts/ first"); process.exit(1); }
let out = "// AUTO-GENERATED by scripts/gen-abis.mjs — do not edit.\n\n";
for (const n of CONTRACTS) {
  const a = JSON.parse(readFileSync(join(OUT, `${n}.sol`, `${n}.json`), "utf8"));
  out += `export const ${n}Abi = ${JSON.stringify(a.abi)} as const;\n\n`;
}
writeFileSync(DEST, out);
console.log("wrote", DEST);
