// Extract the ABIs the ad-server needs from the Foundry build output into a single
// TS module. Re-run after changing contracts: `pnpm abis` (requires `forge build` first).
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "..", "contracts", "out");
const DEST = join(here, "..", "src", "abis.ts");

const CONTRACTS = ["CampaignEscrow", "AuctionHouse", "AttestcoinSettlement", "SourceEngagement", "MockUSDC"];

if (!existsSync(OUT)) {
  console.error(`contracts/out not found at ${OUT}. Run \`forge build\` in contracts/ first.`);
  process.exit(1);
}

let out = "// AUTO-GENERATED by scripts/gen-abis.mjs — do not edit by hand.\n";
out += "// Source: contracts/out/<Name>.sol/<Name>.json\n\n";
for (const name of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(join(OUT, `${name}.sol`, `${name}.json`), "utf8"));
  out += `export const ${name}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}
writeFileSync(DEST, out);
console.log(`wrote ${DEST} (${CONTRACTS.join(", ")})`);
